name: PKGBUILD CI

on:
  workflow_dispatch:

jobs:
  pkgbuild:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Pacman testing repo's
      run: |
        echo "Activating testing repo's..."
        sed -i -e "s/#Include/Include/g" -e "s/#[testing]/[testing]/" -e "s/#[community-testing]/[community-testing]/" /etc/pacman.conf
    - name: Makepkg Build
      id: makepkg
      uses: glitsj16/pkgbuild-action@v1
    - name: Print Package Files
      run: |
        echo "Successfully created the following package archives:"
        echo "${{ steps.makepkg.outputs.pkgfile0 }}"
        echo "${{ steps.makepkg.outputs.pkgfile1 }}"
    - name: Upload Build Artifact0
      uses: actions/upload-artifact@v3.1.2
      with:
        name: "${{ steps.makepkg.outputs.pkgfile0 }}"
        path: "${{ steps.makepkg.outputs.pkgfile0 }}"
    - name: Upload Build Artifact1
      uses: actions/upload-artifact@v3.1.2
      with:
        name: "${{ steps.makepkg.outputs.pkgfile1 }}"
        path: "${{ steps.makepkg.outputs.pkgfile1 }}"
