name: PKGBUILD CI

on:
  workflow_dispatch:

jobs:
  pkgbuild:
    runs-on: ubuntu-latest
    steps:
    - name: Makepkg Build and Check
      id: makepkg
      uses: edlanglois/pkgbuild-action@v1
        inputs:
          pkgdir: "../.."
    - name: Print Package Files
      run: |
        echo "Successfully created the following package archives:"
        echo "${{ steps.makepkg.outputs.pkgfile0 }}"
        echo "${{ steps.makepkg.outputs.pkgfile1 }}"
