name: PKGBUILD CI

on:
  workflow_dispatch:

jobs:
  pkgbuild:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Makepkg Build and Check
      id: makepkg
      uses: glitsj16/pkgbuild-action@v1
    - name: Print Package Files
      run: |
        echo "Successfully created the following package archives:"
        echo "${{ steps.makepkg.outputs.pkgfile0 }}"
        echo "${{ steps.makepkg.outputs.pkgfile1 }}"
