name: PKGBUILD CI

on:
  push:
    paths:
      - 'svf'

jobs:
  pkgbuild:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Makepkg Build
      id: makepkg
      uses: glitsj16/pkgbuild-action@v1
    - name: Print Package Files
      run: |
        echo "Successfully created the following package archives:"
        echo "${{ steps.makepkg.outputs.pkgfile0 }}"
        echo "${{ steps.makepkg.outputs.pkgfile1 }}"
    - name: Upload Build Artifact0
      uses: actions/upload-artifact@v3.1.2
      with:
        name: "${{ steps.makepkg.outputs.pkgfile0 }}"
        path: "${{ steps.makepkg.outputs.pkgfile0 }}"
    - name: Upload Build Artifact1
      uses: actions/upload-artifact@v3.1.2
      with:
        name: "${{ steps.makepkg.outputs.pkgfile1 }}"
        path: "${{ steps.makepkg.outputs.pkgfile1 }}"
